name: Push version tags

on:
  release:
    types: [published]

jobs:
  push-version-tags:
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - name: Push Version Tags
        uses: ovsds/push-version-tags-action@v1
        with:
          version: ${{ github.event.release.tag_name }}
